### ISSUE TITLE
CONNECT POSTGRESSQL

### ISSUE THREAD

**Issue by NguyenManhThuyen123** [Ikhlashmulya/golang-clean-architecture-project-structure#5]
Hey guys, i can't migrate table in my postgresql DB.

When i run -- migrate -database "$DATABASE_URL" -path db/migrations up
it's return no change. Although in DB it exist.

![image](https://github.com/user-attachments/assets/7be169c8-f0e3-4fa5-8515-059628167ad5)

**Comment by Ikhlashmulya** [comment]
Try running a migrate down, then migrate up again

**Comment by NguyenManhThuyen123** [comment]
> Try running a migrate down, then migrate up again

oh i see, i'm very interested in your project.
I wonder why this structure is so little known. hope it will be used more in the future.

i'm adding OpenAPI 3.0 + postgres as a replacement, hope to become a companion of the project in the future
